/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentIntegrityProtocol {
  export type DisputeStruct = {
    executionId: string;
    reason: string;
    resolved: boolean;
  };

  export type DisputeStructOutput = [
    executionId: string,
    reason: string,
    resolved: boolean
  ] & { executionId: string; reason: string; resolved: boolean };
}

export interface AgentIntegrityProtocolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "disputes"
      | "executions"
      | "getDisputes"
      | "raiseDispute"
      | "registerAgent"
      | "storeExecution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "DisputeRaised"
      | "ExecutionStored"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "executions", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getDisputes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storeExecution",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "executions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeExecution",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [owner: AddressLike, name: string];
  export type OutputTuple = [owner: string, name: string];
  export interface OutputObject {
    owner: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [executionId: string, reason: string];
  export type OutputTuple = [executionId: string, reason: string];
  export interface OutputObject {
    executionId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionStoredEvent {
  export type InputTuple = [executionId: string, proofHash: string];
  export type OutputTuple = [executionId: string, proofHash: string];
  export interface OutputObject {
    executionId: string;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentIntegrityProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): AgentIntegrityProtocol;
  waitForDeployment(): Promise<this>;

  interface: AgentIntegrityProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        name: string;
        agentType: string;
        trustScore: bigint;
        stake: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  disputes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean] & {
        executionId: string;
        reason: string;
        resolved: boolean;
      }
    ],
    "view"
  >;

  executions: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean] & {
        executionId: string;
        proofHash: string;
        owner: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  getDisputes: TypedContractMethod<
    [],
    [AgentIntegrityProtocol.DisputeStructOutput[]],
    "view"
  >;

  raiseDispute: TypedContractMethod<
    [executionId: string, reason: string],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [
      name: string,
      agentType: string,
      trustScore: BigNumberish,
      stake: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  storeExecution: TypedContractMethod<
    [executionId: string, proofHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        name: string;
        agentType: string;
        trustScore: bigint;
        stake: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean] & {
        executionId: string;
        reason: string;
        resolved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executions"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean] & {
        executionId: string;
        proofHash: string;
        owner: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDisputes"
  ): TypedContractMethod<
    [],
    [AgentIntegrityProtocol.DisputeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [executionId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      name: string,
      agentType: string,
      trustScore: BigNumberish,
      stake: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeExecution"
  ): TypedContractMethod<
    [executionId: string, proofHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionStored"
  ): TypedContractEvent<
    ExecutionStoredEvent.InputTuple,
    ExecutionStoredEvent.OutputTuple,
    ExecutionStoredEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "DisputeRaised(string,string)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "ExecutionStored(string,string)": TypedContractEvent<
      ExecutionStoredEvent.InputTuple,
      ExecutionStoredEvent.OutputTuple,
      ExecutionStoredEvent.OutputObject
    >;
    ExecutionStored: TypedContractEvent<
      ExecutionStoredEvent.InputTuple,
      ExecutionStoredEvent.OutputTuple,
      ExecutionStoredEvent.OutputObject
    >;
  };
}
